name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Upload .env to VPS
      run: |
        echo "${{ secrets.ENV_FILE }}" | ssh root@147.93.9.109 "mkdir -p /var/www/mnotas && cat > /var/www/mnotas/.env"

    - name: Deploy to VPS
      run: |
        ssh root@147.93.9.109 << 'EOF'
          set -e

          cd /var/www

          if [ ! -d "mnotas" ]; then
            git clone https://github.com/MiqueiasSB/MNotas-v2.git mnotas
          fi

          cd mnotas
          git config --global --add safe.directory /var/www/mnotas

          # Atualiza o repositório com segurança
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          # Permissões adequadas
          chown -R www-data:www-data .
          chmod -R 775 .
          chown -R www-data:www-data storage bootstrap/cache
          chmod -R ug+rwX storage bootstrap/cache

          # Instala dependências via container
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v $(pwd):/app \
            -w /app \
            laravelsail/php82-composer:latest \
            composer install --no-interaction --prefer-dist --optimize-autoloader

          # Sobe os containers do Sail
          ./vendor/bin/sail up -d --build

          # Espera o MySQL iniciar
          RETRIES=15
          COUNT=0
          until ./vendor/bin/sail exec mysql sh -c 'mysqladmin ping -hmysql --silent'; do
            COUNT=$((COUNT+1))
            if [ $COUNT -ge $RETRIES ]; then
              echo "⛔️ MySQL não respondeu após $RETRIES tentativas."
              exit 1
            fi
            echo "⏳ Aguardando MySQL... ($COUNT/$RETRIES)"
            sleep 2
          done

          # Comandos Laravel
          ./vendor/bin/sail artisan migrate --force
          ./vendor/bin/sail artisan optimize
        EOF
