name: Deploy to VPS

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Upload .env to VPS
      run: |
        echo "${{ secrets.ENV_FILE }}" | ssh root@147.93.9.109 "cat > /var/www/mnotas/.env"

    - name: Deploy to VPS
      run: |
        ssh root@147.93.9.109 << 'EOF'
          set -e

          mkdir -p /var/www/mnotas
          cd /var/www/mnotas

          # Clona o projeto se ainda não existir
          if [ ! -d ".git" ]; then
            git clone https://github.com/MiqueiasSB/MNotas-v2.git .
          else
            git pull origin main
          fi

          chown -R root:root .

          docker run --rm -v $PWD:/app -w /app laravelsail/php82-composer:latest composer install --no-interaction --prefer-dist --optimize-autoloader

          ./vendor/bin/sail up -d --build

          ./vendor/bin/sail artisan optimize
          ./vendor/bin/sail artisan migrate --force
        EOF

